### ISSUE TITLE
Using index to access Config properties triggers errors in strict mode 

### ISSUE THREAD

**Issue by mishok13** [schubergphilis/microchassis#24]
When using `--strict` config option in `tsc` the following code will produce an error `TS7017: Element implicitly has an 'any' type because type 'Config' has no index signature.`:
```
const config = new Config();
const foo = config['foo'];
```

**Comment by rthewhite** [comment]
You can now access them using a get function on the config object:
`const config = new Config();
const foo = config.get('foo')`
